### ISSUE TITLE
JitStreamer.sh not executing

### ISSUE THREAD

**Issue by theveloperspl** [jawshoeadan/AlpineJitVM#1]
When I follow steps in readme script is not executing.
After typing ./JitStreamer.sh nothing happens and new line prompt appears.
When I copy and paste content of script into terminal everything works like it should.

**Comment by jawshoeadan** [comment]
Yeah I think I messed up the original VM to have an empty script, but I just uploaded a new release that should be fixed, lmk if it works for you. Otherwise, you can run `wget https://raw.githubusercontent.com/jawshoeadan/AlpineJitVM/refs/heads/main/JitStreamer.sh -O JitStreamer.sh` then it should work.
